### ISSUE TITLE
docker  kspider-ui运行登录后，页面出现问题

### ISSUE THREAD

**Issue by yinqinghe** [kkangert/kspider-ui#9]
![image](https://github.com/user-attachments/assets/d6ba8569-e463-4ac4-97b2-984b5fb19ba9)

**Comment by kkangert** [comment]
> ![image](https://github.com/user-attachments/assets/d6ba8569-e463-4ac4-97b2-984b5fb19ba9)
> 

请检查cookie设置是否正常

**Comment by coding-climber** [comment]
> ![image](https://private-user-images.githubusercontent.com/70678389/354874432-d6ba8569-e463-4ac4-97b2-984b5fb19ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTgxMjIsIm5iZiI6MTcyMzYxNzgyMiwicGF0aCI6Ii83MDY3ODM4OS8zNTQ4NzQ0MzItZDZiYTg1NjktZTQ2My00YWM0LTk3YjItOTg0YjVmYjE5YmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDk2Y2NjNDIwZDRmNWE5ZmYxZDExMjUxNmM3OTI2MjRmMjk5ZWM0ZDUwMzEwNjJjODViMzA2YTQ0N2MxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AHktu0oSFmS1F96TLaTFNXlVPN2Of2bVIW_MZMCTzig)

点开浏览器得cookie，把secure那一项勾选取消掉就可以登进去了

**Comment by kkangert** [comment]
> > ![image](https://private-user-images.githubusercontent.com/70678389/354874432-d6ba8569-e463-4ac4-97b2-984b5fb19ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTgxMjIsIm5iZiI6MTcyMzYxNzgyMiwicGF0aCI6Ii83MDY3ODM4OS8zNTQ4NzQ0MzItZDZiYTg1NjktZTQ2My00YWM0LTk3YjItOTg0YjVmYjE5YmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDk2Y2NjNDIwZDRmNWE5ZmYxZDExMjUxNmM3OTI2MjRmMjk5ZWM0ZDUwMzEwNjJjODViMzA2YTQ0N2MxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AHktu0oSFmS1F96TLaTFNXlVPN2Of2bVIW_MZMCTzig)
> 
> 点开浏览器得cookie，把secure那一项勾选取消掉就可以登进去了

主要是cookie后端设置了secure策略

**Comment by kkangert** [comment]
https://github.com/kkangert/kspider/pull/32

**Comment by elarbor** [comment]
对应的后端项目是https://github.com/kkangert/kspider 吗？
